# Generated by Django 5.2.7 on 2025-11-05 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='app_payment_order_i_eddc9e_idx',
            old_name='transaction_order_i_d88f29_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='app_payment_created_233761_idx',
            old_name='transaction_created_9e294f_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='app.paymentmethod'),
        ),
    ]
