# Generated by Django 5.2.7 on 2025-11-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_paymentmethod_remove_payment_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('compensated', 'Compensated')], db_index=True, default='success', max_length=20),
        ),
    ]
